### ISSUE TITLE
Table of contents not updated / long ToC causes wrong page numbers

### ISSUE THREAD

**Issue by 240ch** [gallandarakhneorg/autolatex#101]
I think the latex-command isn't run a second time after updating toc, glossaries and bibliography. I use the following MWE:

```
\documentclass{article}
\usepackage{blindtext}
\begin{document}
\tableofcontents
\section{First section}
\Blindtext
\section{Second section}
\blindtext
\section{Another section on page 4}
\section{Another section}
\section{Another section}
\section{Another section}
\section{Another section}
\section{Another section}
\section{Another section}
\section{Another section}
\section{Another section}
\section{Another section}
\section{Another section}
\section{Another section}
\section{Another section}
\section{Another section}
\section{Another section}
\section{Another section}
\section{Another section}
\section{Another section}
\section{Another section}
\section{Another section}
\section{Another section}
\end{document}
```

If you name it `doc.tex` and compile it with `autolatex -f doc.tex --pdf`, the generated PDF has wrong page numbers in the table of contents. Another run updates them correctly. Is there an option I'm missing to set or could autolatex be improved to have the compile command run a second time?

**Comment by gallandarakhneorg** [comment]
AutoLaTeX is supposed to detect when pdflatex must be run more than once (for updating the references, including the table of content). I will explore this issue today.

**Comment by gallandarakhneorg** [comment]
This is an interesting issue. I have tried to launch by hand the pdflatex command. I'm needing 3 calls to pdflatex for obtaining the correct page numbers.

After the second call to pdflatex, I obtain the following log file:
```
This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013/Debian) (format=pdflatex 2014.11.3)  21 FEB 2016 22:32
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**doc.tex
(./doc.tex
LaTeX2e <2011/06/27>
Babel <3.9h> and hyphenation patterns for 4 languages loaded.
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2007/10/19 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2007/10/19 v1.4h Standard LaTeX file (size option)
)
\c@part=\count79
\c@section=\count80
\c@subsection=\count81
\c@subsubsection=\count82
\c@paragraph=\count83
\c@subparagraph=\count84
\c@figure=\count85
\c@table=\count86
\abovecaptionskip=\skip41
\belowcaptionskip=\skip42
\bibindent=\dimen102
) (./doc.aux)
\openout1 = `doc.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 3.
LaTeX Font Info:    ... okay on input line 3.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 3.
LaTeX Font Info:    ... okay on input line 3.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 3.
LaTeX Font Info:    ... okay on input line 3.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 3.
LaTeX Font Info:    ... okay on input line 3.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 3.
LaTeX Font Info:    ... okay on input line 3.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 3.
LaTeX Font Info:    ... okay on input line 3.

(./doc.toc)
\tf@toc=\write3
\openout3 = `doc.toc'.

 [1

{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}] [2] [3]
Overfull \vbox (27.95787pt too high) has occurred while \output is active []


[4] (./doc.aux) ) 
Here is how much of TeX's memory you used:
 211 strings out of 494999
 2209 string characters out of 6180228
 60974 words of memory out of 5000000
 3510 multiletter control sequences out of 15000+600000
 4553 words of font info for 17 fonts, out of 8000000 for 9000
 14 hyphenation exceptions out of 8191
 23i,4n,17p,2826b,109s stack positions out of 5000i,500n,10000p,200000b,80000s
</usr/share/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/
cmbx10.pfb></usr/share/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmbx12
.pfb></usr/share/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb>
Output written on doc.pdf (4 pages, 37538 bytes).
PDF statistics:
 29 PDF objects out of 1000 (max. 8388607)
 19 compressed objects within 1 object stream
 0 named destinations out of 1000 (max. 500000)
 1 words of extra memory for PDF output out of 10000 (max. 10000000)
```

Unfortunately, there is nothing inside this file that indicates the need to invoke pdflatex, as usually done for missed references, etc.

That's why autolatex is not generating the correct pdf. autolatex is scanning the log file for determining if a relaunch of pdflatex is needed.

From these results, I'm confused to say that this issue cannot be solve by autolatex easily.
We could force autolatex to launch pdflatex at least 3 times. But it is not the best solution because some documents need only one or two calls to pdflatex.

I have not yet found an explanation of this behavior of pdflatex on Internet. If someone could help, he/she is welcome.

**Comment by gallandarakhneorg** [comment]
I have asked to the LaTeX community to give me a feedback on this issue: 
http://latex-community.org/forum/viewtopic.php?f=5&t=27164

**Comment by gallandarakhneorg** [comment]
For fixing this issue, I propose to add a command line option and a configuration file entry that enable to specify the number of times pdflatex should be run during the last stage of autolatex. Until now, only one run was assumed. We may solve this issue by passed a higher number with this new command line option.

**Comment by 240ch** [comment]
Thank you for investigating. I agree, let's try it your proposed way.

**Comment by 240ch** [comment]
Perfect, now everything is working: LuaTeX with bibliography, glossary and ToC is also up-to-date. I verified all those commands:
`autolatex -f doc.tex --lualatex --biblio --gloss --postcompilationruns=2`

Thank you very much, I appreciate your efforts.

**Comment by gallandarakhneorg** [comment]
Your're welcome.
Options `--biblio` and `--gloss` could be removed from your command line since they are enabled by default.
