### ISSUE TITLE
Multiple indices

### ISSUE THREAD

**Issue by PatrickMassot** [gallandarakhneorg/autolatex#106]
I'm not this is a question or a feature request (or a bug report). I'm trying to compare currently available LaTeX build systems and this is my first day using autolatex. Say I have a document with several indices, like the following ``test.tex``:

```latex
\documentclass{article}

\usepackage[xindy]{indextools}
\makeindex[name=authors, title=Autors index]
\makeindex[name=subjects, title=Subject index]


\begin{document}
  Gromov invented holomorphic curves in symplectic
  manifolds\index[authors]{Gromov}\index[subjects]{Symplectic manifold}. 
	
\printindex[authors]
\printindex[subjects]
\end{document}
```

Compiling by hand means:
```bash
xelatex test
texindy subjects.idx
texindy authors.idx
xelatex test
```
This produces [test.pdf](https://github.com/gallandarakhneorg/autolatex/files/1382485/test.pdf).
In order to do that with ``latexmk`` you only need the following latexmkrc:
```
$pdf_mode = "1";
$pdflatex = "xelatex %S";
$makeindex = "texindy %S";
```
It will find both indices. What would be the corresponding ``.autolatex_project.cfg``?

**Comment by gallandarakhneorg** [comment]
From the command line, only the LaTeX compiler could be changed easily.
```bash
autolatex --xelatex
```

Within the configuration file, all could be changed:
```ini
[Generation]
tex compiler = xelatex
makeindex_cmd = texindy
makeindex_flags = 
```

Do you need to launch texindy two times?

**Comment by PatrickMassot** [comment]
texindy is run twice because there are two .ind files. Have you tried to compile my example using autolatex?

**Comment by gallandarakhneorg** [comment]
I didn't. AutoLaTeX needs to be patched in order to parse the `\makeindex` arguments.
Indeed, AutoLaTeX assumes the standard prototype for this macro, i.e. without argument.

In its current state, AutoLaTeX search for the file `test.idx` for compiling the index table.

**Comment by PatrickMassot** [comment]
Ok, thanks for this explanation and good luck with patching. I wish I could help but I gave up learning Perl when I discovered python...

**Comment by gallandarakhneorg** [comment]
No problem. I will publish it during the week end.
I will provide a Python version of autolatex as soon as possible. And, let the Perl version finishing its life without new features.

**Comment by PatrickMassot** [comment]
Thank you very much for this super quick improvement. A python version would be awesome. Then latexmk would be in real trouble, especially if the python version is easily available using pip.

I still have a basic question. I'm confused by the command line targets. With the config file you wrote, I can compile my document and get my indices simply by typing autolatex. But if I add a bibliography then I need to type ``autolatex all biblio all`` to get everything correct. Is that the intended procedure?

**Comment by gallandarakhneorg** [comment]
I usually use `autolatex clean all`. The default cli target is "all".
If you still encoutering issues, please type `autolatex -vvv <targets>` and put it in a new issue.

Regarding the Python version, unfortunately I have no enough free time to work on it hard. I expect to have something equivalent to Perl version in 2019.
