### ISSUE TITLE
biblatex indexing

### ISSUE THREAD

**Issue by PatrickMassot** [gallandarakhneorg/autolatex#109]
Biblatex allows to add entries into some index file each time \cite is used. Example test.tex:
```latex
\documentclass{article}

\usepackage[backend=biber, indexing=cite]{biblatex}
\addbibresource{biblio.bib}

\usepackage[xindy]{indextools}
\makeindex

\begin{document}
  \cite{Gromov_HolCurves}.

  \printindex
  \printbibliography
\end{document}
```
with some corresponding biblio.bib:
```bibtex
@Article{   Gromov_HolCurves,
  author  = "Gromov, Misha",
  title   = {Pseudo holomorphic curves in symplectic manifolds},
  journal = "Invent. Math.",
  volume  = 82,
  pages   = "307--347",
  year    = 1985,
}
```

Correct build sequence is: 
* xelatex test  (creates test.aux mentioning a cite and an empty test.idx)
* biber test (creates a bbl file)
* xelatex test (only now test.idx becomes non-empty)
* texindy test.idx (creates test.ind)
* xelatex test (reads test.ind to get final result)

autolatex misses the xelatex invocation between biber and texindy (and adds a final xelatex for some reason).

**Comment by gallandarakhneorg** [comment]
AutoLaTeX detects when some references are still missed after generating the PDF file. I think that's why xelatex is launch two times after texindy.
Nevertheless, I did not implement a latex launch between the bibliography and indexers. I could add that.

**Comment by gallandarakhneorg** [comment]
This feature will be added into the Python implementation of AutoLaTeX. The Perl version is frozen.
