### ISSUE TITLE
astah2pdf not working with astah_community

### ISSUE THREAD

**Issue by ssardina** [gallandarakhneorg/autolatex#110]
First thing is that astah_community comes with jar file `astah-community.jar` which is missing in list of jars:

https://github.com/gallandarakhneorg/autolatex/blob/master/translators/astah2pdf.transdef#L36

Once that is added to the list of possible libraries there is bigger problem: class `com.change_vision.jude.cmdline.JudeCommandRunner` does not support translation to svg, maybe it was supported in the past and not now, juts png and jpg. So `-t svg` in this line crashes:

https://github.com/gallandarakhneorg/autolatex/blob/master/translators/astah2pdf.transdef#L99

Now, I am wondering whether astah2pdf is done only for the pro versions where maybe svg can be produced? I say this because astah2png does have the `astah-community.jar` file listed, so... so maybe in the end this was not a bug or a non-updated translator, it's just that astah2pdf cannot be used with the community version of astah. Could that be the case?

I have configured my autolatex to produce png for astah and seems to pass this issue...

**Comment by gallandarakhneorg** [comment]
Dear @ssardina.
Ineed, this is not a bug. The PDF exporter exists only within the "Professsional" edition of Astah.
While you are using the "Community" edition, you have to export the diagram to PNG.

**Comment by ssardina** [comment]
yes I figured that out after checking the code translation..

after understanding it a bit more I realize this is in

http://www.arakhne.org/autolatex/doc.html

because astah-com is not listed in the pdf conversion!
