### ISSUE TITLE
List the converters for MacOS and Windows platforms

### ISSUE THREAD

**Issue by gallandarakhneorg** [gallandarakhneorg/autolatex#81]
To be used on MacOS and Windows platforms, a list of the external conversion software should be provided. In this way, I may put in AutoLaTeX the corresponding translators.

If you are a MacOS or Windows user, please write a comment for updating or completing the table below. If you are able to provide the tool name, and the command line, it will be better.

| Input Format | Output format | MACOS | Windows | Linux |
| --- | --- | --- | --- | --- |
| .asta | .pdf | Astah | Astah | Astah |
| .asta | .png | Astah | Astah | Astah |
| .asy | .pdf | asy |  | asy |
| .c .cpp | .tex | texify | texify | texify |
| .dia | .pdf |  |  | dia |
| .dot | .pdf | dot from Graphviz | dot from Graphviz | dot from Graphviz |
| .dot | .png | dot from Graphviz | dot from Graphviz | dot from Graphviz |
| .dot | .tex | dot from Graphviz | dot from Graphviz | dot from Graphviz |
| .eps | .pdf |  |  | epstopdf or ps2pdf |
| .fig | .pdf |  |  | fig2dev |
| .ggb | .pdf | GeoGebra | GeoGebra | GeoGebra |
| .gle | .pdf |  |  | gle |
| .gle | .png |  |  | gle |
| .gnu | .pdf | gnuplot | gnuplot | gnuplot |
| .gxl | .pdf |  |  | gxl2dot |
| .gxl | .png |  |  | gxl2dot |
| .h .hpp | .tex | texify | texify | texify |
| .&lt;img&gt;.gz | .&lt;img&gt; | zcat |  | zcat |
| .java | .tex | texify | texify | texify |
| .jude | .pdf | Astah | Astah | Astah |
| .jude | .png | Astah | Astah | Astah |
| .juth | .pdf | Astah | Astah | Astah |
| .juth | .png | Astah | Astah | Astah |
| .lisp | .tex | texify | texify | texify |
| .m | .tex | texify | texify | texify |
| .ml | .tex | texify | texify | texify |
| .oct | .pdf | GNU octave | GNU octave | GNU octave |
| .oct | .png | GNU octave | GNU octave | GNU octave |
| .odg | .pdf | libreoffice or openoffice | libreoffice or openoffice | libreoffice or openoffice |
| .perl | .tex | texify | texify | texify |
| .plot | .pdf | gnuplot | gnuplot | gnuplot |
| .py | .tex | texify | texify | texify |
| .rb | .tex | texify | texify | texify |
| .sql | .tex | texify | texify | texify |
| .svg | .pdf |  |  | inkscape |
| .svg | .png |  |  | inkscape |
| .vsd | .pdf |  |  | inkscape |
| .vdx | .pdf |  |  | inkscape |
| .vsdx | .pdf |  |  | inkscape |
| .xcf | .pdf |  |  | imagemagick |
| .xcf | .png |  |  | imagemagick |
| .xmi | .pdf |  |  | umbrello, uml2svg, or xmi2svg |

**Comment by pabloferz** [comment]
`texify` is a perl script isn't it? As you can install Perl on MacOS and WIndows I believe it should be really easy to use it in the same cases where `textify` is already used.

As for the other tools. I will try to help in finding out the tools needed. I guess that in a lot of cases a lot of the programs already used would have MacOS and Windows versions.

**Comment by gallandarakhneorg** [comment]
Thank you. I updated the table above.
