### ISSUE TITLE
Rewrite AutoLaTeX in Python?

### ISSUE THREAD

**Issue by gallandarakhneorg** [gallandarakhneorg/autolatex#84]
Is it an interesting idea to rewrite AutoLaTeX in Python?

This language is used from writing plugins in a lot of softwares. Providing Python code for AutoLaTeX may help to create integrated version of AutoLaTeX.

**Comment by pabloferz** [comment]
This is a nice idea. Maybe a branch can be created where the equivalent Python code can be slowly added and tested. I am not a Perl programmer but I can help with the Python version.

**Comment by gallandarakhneorg** [comment]
I agree. Since I have no time do start this task until end of 2015, I delay the recoding.
You're welcome to contribute :smile:

**Comment by gallandarakhneorg** [comment]
Branch 'full_python' contains the future version of AutoLaTeX, written in Python.
