### ISSUE TITLE
Add tikz support.

### ISSUE THREAD

**Issue by gallandarakhneorg** [gallandarakhneorg/autolatex#92]
The tikz figures are TeX figures that may be included in the document.
AutoLaTeX may provide a translator for converting `.tikz` files to PDF.

**Comment by pabloferz** [comment]
I believe you can compile `.tikz` files from a terminal by using a script like this

```bash
for f in *.tikz
do 
  jn=$(basename $f .tikz)
  pdflatex -jobname $jn "\documentclass{standalone}\usepackage{pgfplots,amsmath}\begin{document}\input{$f}\end{document}"
  rm $jn.aux $jn.log
done
```

Maybe a translator that does that might work.

**Comment by gallandarakhneorg** [comment]
Thank you I will create a translator based on this short script.
