### ISSUE TITLE
Incorrect pasing of latex_flags in Make.pm

### ISSUE THREAD

**Issue by neok-m4700** [gallandarakhneorg/autolatex#98]
Shouldn't line 292 [ push @{$self->{'latex_flags'}}, @params; ]

be replaced by : [ push @{$self->{'latex_cmd'}}, @params; ]

in pm/AutoLaTeX/Make/Make.pm ?

**Comment by gallandarakhneorg** [comment]
Seems not.
'latex_flags' contains the command-line parameters for LaTeX command.
'latex_cmd' contains the executable of LaTeX.

Is there an unexpected behavior related to your issue?

Currently, the Perl version of AutoLaTeX is maintained for bug fixes and backward compatibility.
I'm working on a python version of AutoLaTeX (in the 'full-python' branch) that should be the next generation for this tools.

**Comment by neok-m4700** [comment]
Thank you for your answer.

What I don't understand is where the 'latex_flags' are interpreted in the code.

In Make.pm, latex_cmd is in finally interpreted l. 658 or 666:
```perl 
$exitcode = runCommandSilently(@{$self->{'latex_cmd'}} [...];
```
, but I couldn't find any trace of latex_flags elsewhere than l. 292:
```perl 
push @{$self->{'latex_flags'}}, @params;
```

The unexpected behavior is that when I use a local .autolatex_project.cfg as following:
```cfg
[generation]
latex_cmd = lualatex
latex_flags = -synctex=1

[svg2png_rsvg]
include module = no

[svg2pdf_rsvg]
include module = no

[svg2pdf_inkscape]
include module = no
```
, then run autolatex on a sample foo.tex file as following:
```latex
\documentclass{article}

\begin{document}
  Hello world !
\end{document}
```
=> I do not have any synctex.gz files produced, meaning that the flags given: latex_flags = -synctex=1 were not interpreted.

If I change in Make.pm l.292 by:
```perl
push @{$self->{'latex_cmd'}}, @params;
```

, and then issue `./Makefile.PL; make; sudo make install`, plus rerun autolatex

=> A synctex.gz file is now present, meaning the latex_flags were interpreted.

I hope I made myself clear.

I am not a Perl expert, but I mostly work with python. Do you need any help on developing the python version ?

**Comment by gallandarakhneorg** [comment]
Indeed, this is an issue. The flags must be added to `*_cmd`.
