### ISSUE TITLE
--lualatex throws "! Undefined control sequence. l.1 \documentclass"

### ISSUE THREAD

**Issue by 240ch** [gallandarakhneorg/autolatex#99]
I'm trying to compile my LuaTeX document with `autolatex -f document.tex --lualatex --pdf --stderr --biblio` but it doesn't seem to work. I'm getting the above mentioned exception. 

Using `lualatex document.tex` directly works. Is it possible that you try to compile the document with `luatex` instead of `lualatex` (http://tex.stackexchange.com/questions/27144/documentclass-undefined-control-sequence/27148#27148)? Because those error messages look the same to me:

```
user@ubuntu-user:~/git-directory$ more document.log 
This is LuaTeX, Version beta-0.76.0-2013121407 (rev 4627)  (format=luatex 2016.2.16)  17 FEB 2016 09:02
 restricted \write18 enabled.
 file:line:error style messages enabled.
**document.tex
(./document.tex
./document.tex:1: Undefined control sequence.
l.1 \documentclass
                [paper=a4,
./document.tex:1:  ==> Fatal error occurred, no output PDF file produce
d!

user@ubuntu-user:~/git-directory$ luatex document.tex 
This is LuaTeX, Version beta-0.76.0-2013121407 (rev 4627) 
 restricted \write18 enabled.
(./document.tex
! Undefined control sequence.
l.1 \documentclass
                [paper=a4,

```

**Comment by gallandarakhneorg** [comment]
Fixing in version 38.3.
